<a href="https://colab.research.google.com/github/maratteokbokki/AIpython/blob/main/250509.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [2]:
b = np.array([[1, 2], [3, 4]])
print(b)

[[1 2]
 [3 4]]


라이브러리 불러오는
라이브러리=함수=모듈
내부: 마음대로 쓸 수 있는~ print / 단어()이며 함수 형태 - 내장되어있는
외부: 불러와서 쓰는 거(pip로 인스톨)
사용자 정의: 라이브러리를 만들지도!! = 사용자 정의
import로 불러오기
메소드(모듈의 기능)
요구 사항에 대한 라이브러리를 찾아서 쓰기
흐름 보기-> 그래프 / 주석으로 정보 자세히 표시라이브러리 불러오는
라이브러리=함수=모듈
내부: 마음대로 쓸 수 있는~ print / 단어()이며 함수 형태 - 내장되어있는
외부: 불러와서 쓰는 거(pip로 인스톨)
사용자 정의: 라이브러리를 만들지도!! = 사용자 정의
import로 불러오기
메소드(모듈의 기능)
요구 사항에 대한 라이브러리를 찾아서 쓰기
흐름 보기-> 그래프 / 주석으로 정보 자세히 표시
입력(매개변수) -> 함수(작은 프로그램) -> 출력
함수는 외부 껍데기만 보인다
enumerate= 내부함수 / 인덱스와 값을 반환하는 함수
for문에서 i가 출력
value+10 = 주석 가독성 좋게 만드는 것(점에서 조금 떨어져서)
str() = 내부함수
ha= 수평 (center=중앙정렬)
va= 수직 (bottom 아래 정렬)
배열=리스트
2차원리스트=괄호 안에 괄호 또 있음(행렬구조)
numpy=외부 라이브러리
pip list = 목록확인
numpy 사이트에서 버전 찾기
버전 맞추기 필수
type() = 어떤 종류인지 알려주는 함수
넘파이 객체의 메소드
괄호 없으면 속성
메소드의 출처를 알아야(이건 판다스메소드.이건넘파이메소드)



In [10]:
import pandas as pd

In [12]:
s = pd.Series([10, 20, 30, 40])
type(s)

pandas.core.series.Series

데이터 행과 열로 구분(데이터프레임구조) = 엑셀구조


In [3]:
import numpy as np

arr = np.zeros(5)
print(arr)

[0. 0. 0. 0. 0.]


In [4]:
arr = np.arange(2, 11, 2)
print(arr)

[ 2  4  6  8 10]


In [5]:
a = np.array([2, 4, 6])
b = np.array([10, 20, 30])

result = a * b
print(result)

[ 20  80 180]


In [6]:
filtered = result[result > 20]
print(filtered)

[ 80 180]


In [9]:
print(np.arange(2, 11, 2))

[ 2  4  6  8 10]


In [16]:
data = {
    '이름': ['홍길동', '김철수', '이영희'],
    '나이': [25, 30, 27],
    '성별': ['남', '남', '여']
}

df = pd.DataFrame(data)
print(df)

    이름  나이 성별
0  홍길동  25  남
1  김철수  30  남
2  이영희  27  여


In [17]:
df.to_csv('output_students.csv', index=False)

In [18]:
df = pd.read_csv('output_students.csv')
print(df.head())

    이름  나이 성별
0  홍길동  25  남
1  김철수  30  남
2  이영희  27  여


In [21]:
df1 = pd.read_csv('train_and_test2.csv')

df = pd.DataFrame(data) 딕셔너리를 데이터프레임구조로
csv=텍스트
캐글 = 데이터사이언스커뮤니티 / 샘플 다량, 데이터 얻기 가능
빈값 없애기, 채우기


In [19]:
df[df['나이'] > 25]

이름  나이 성별
1  김철수  30  남
2  이영희  27  여

In [22]:
result = df1.groupby('Sex')['Age'].mean()
print(result)

Sex
0    30.017888
1    28.572082
Name: Age, dtype: float64
